# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-04 09:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Probicipant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=80)),
                ('affiliation', models.CharField(max_length=100)),
                ('position', models.CharField(choices=[('MAS', 'Master student'), ('PHD', 'PhD Student'), ('POS', 'Postdoctoral Fellow'), ('ENG', 'Research Engineer'), ('RES', 'Researcher'), ('OTH', 'Other')], default='OTH', max_length=3)),
                ('position_other', models.CharField(blank=True, default='', max_length=30, verbose_name='If other, specify')),
                ('doctoral_school', models.CharField(blank=True, default='', help_text='for PhD students', max_length=30)),
                ('research_domain', models.CharField(max_length=40)),
                ('motivations', models.TextField(help_text='Explain why you want to attend                                               this workshop (max 300 char)', max_length=300)),
                ('programming_languages', models.CharField(blank=True, default='', help_text='What are the                                                         programming languages                                                        you are familiar with', max_length=40)),
                ('python_level', models.CharField(choices=[('BEG', 'Beginner'), ('INT', 'Intermediate'), ('ADV', 'Advanced')], default='BEG', max_length=3)),
            ],
        ),
    ]
