# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-07 09:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='probicipant',
            name='dietary',
            field=models.CharField(choices=[('OMN', 'Omnivore'), ('VEG', 'Vegetarian')], default='OMN', max_length=3),
        ),
    ]
