# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-19 14:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontapp', '0002_probicipant_dietary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='probicipant',
            name='dietary',
            field=models.CharField(choices=[('OMN', 'Omnivore'), ('VEG', 'Vegetarian')], default='OMN', max_length=3, verbose_name='Dietary restrictions'),
        ),
    ]
